services:
  npm-db:
    image: 'jc21/mariadb-aria:latest'
    container_name: artax-npm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm_root_password'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm_password'
    volumes:
      - ./npm/mysql:/var/lib/mysql
    networks:
      - artax-network

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: artax-npm
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:81:81'
      #- '81:81'  # <--- REMOVED 127.0.0.1: so it's accessible via VPN  if you want to make it public
    environment:
      DB_MYSQL_HOST: "artax-npm-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm_password"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
      - /opt/artax/npm/ssl/:/etc/nginx/ssl   # <--- Add this line
    depends_on:
      - npm-db
    networks:
      - artax-network

  artax-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artax-frontend
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - artax-network
    depends_on:
      - nginx-proxy-manager

networks:
  artax-network:
    external: true